In [24]:
a = np.arange(6).reshape(3,2)
b = np.arange(6, 12).reshape(3,2)

print(a)
print()
print(b)

c = np.vstack((a,b))

d = np.hstack((a,b))
print("vertical stack")
print(c)
print("horizontal stack")
print(d)
print("concatenate")

print(np.concatenate((a,b), axis=0))

[[0 1]
 [2 3]
 [4 5]]

[[ 6  7]
 [ 8  9]
 [10 11]]
vertical stack
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
horizontal stack
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]
concatenate
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [56]:
a = np.arange(30).reshape(2,15)

result = np.hsplit(a, 3)#Decoupage horizontale en fonction du nombre de colones
print("---------------Decoupage horizontale en fonction du nombre de colones------------")
print(a)
print("\n",result[0])
print("\n",result[1])
print("\n",result[2])


result = np.vsplit(a, 2)#Decoupage verticale en fonction du nombre de lignes
print("\n---------------Decoupage verticale en fonction du nombre de lignes------------")
print(a)
print("\n",result[0])
print("\n",result[1])
#print("\n",result[2])

---------------Decoupage horizontale en fonction du nombre de colones------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]

 [[ 0  1  2  3  4]
 [15 16 17 18 19]]

 [[ 5  6  7  8  9]
 [20 21 22 23 24]]

 [[10 11 12 13 14]
 [25 26 27 28 29]]

---------------Decoupage verticale en fonction du nombre de lignes------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]

 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [73]:
a = np.arange(12).reshape(3,4)
b = a  > 4
print(a)
print()
print(b)
print()
print(a[b])#affiche tous les éléments qui sont True dans le masque b


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

[ 5  6  7  8  9 10 11]


In [80]:
a = np.arange(12).reshape(3,4)
b = a  > 4
print(b)
c = a < 4
print()
print(c)
print()
print(a[a<4])
print()
print(a[a>4])

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

[[ True  True  True  True]
 [False False False False]
 [False False False False]]

[0 1 2 3]

[ 5  6  7  8  9 10 11]
