In [2]:
import numpy as np
 
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a[0]

1

In [25]:
np.random.randn(5, 4)

array([[ 1.06101021,  1.55840458, -0.38492913, -1.14028448],
       [-0.1871812 ,  0.26725222,  1.53305661, -0.78153014],
       [ 1.1726517 ,  1.20015676, -1.75212064, -0.98221465],
       [-0.76233862,  0.21478106,  0.54173902,  0.23718724],
       [-0.2063776 , -0.10380742,  0.31834757, -1.29780768]])

In [26]:
np.full((4, 9), 100)

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [9]:
b = np.zeros((4, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((4, 4))

a = np.ones((4, 4))
a


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
c = np.concatenate((a, b), axis =1)
print(c.shape)
print(c)
print()
print(c[0:3, :4])
print()
print(c[0:, 2:5])

(4, 8)
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]


In [5]:
np.linspace(0, 10, 4).ndim

1

In [6]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])