In [2]:
import numpy as np

In [64]:
array = np.array([1, 2, 3])

print(array.itemsize)#la taille en octet de chaque éléments vaut 4 dans notre cas
print(array.size)#la taille totale ou le nombre de tous les éléments présents dans le tableau

4
3


In [4]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((5, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [9]:
x = np.full((10, 20), 4)


In [10]:
x.ndim

2

In [11]:
x.size

200

In [12]:
x.dtype

dtype('int32')

In [13]:
x.shape

(10, 20)

In [14]:
x[0,1]

4

In [16]:
x[0,1] = 3

In [18]:
x

array([[4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [19]:
x[0,1] = 3.14 # la nouvelle valeure est converti par defaut en entier 
x

array([[4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [20]:
type(x)

numpy.ndarray

In [22]:
x.dtype


dtype('int32')

In [36]:
#Un tableau de taile 6 (6 Nombre) aléatoire dans un botte de nombre compris entre 0 et 10
x = np.random.randint(10, size=6)#
x

array([1, 3, 5, 0, 7, 6])

In [37]:
x[0:2]

array([1, 3])

In [39]:
x[:2]

array([1, 3])

In [45]:
x[0: :2] # Le deuxieme chiffre 2 represente le pas

array([1, 5, 7])

In [51]:
def calcule_inverse(values):
    output = np.empty(len(values)) #output est un tableau vide de taille -->len(values)
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [59]:
tableau_large = np.random.randint(1,10, size = 100)#tableau de 1000000 de nombres aléatoires dans un botte de 1 à 10 

In [65]:
%timeit (1.0/tableau_large)

9.85 µs ± 51.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [66]:
%timeit calcule_inverse(tableau_large)

1.56 ms ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# NEXT TUTORIAL