In [51]:
import numpy as np
import time
import sys
a = np.array([1,2,3])

In [6]:
a[0]

1

In [7]:
a[2]

3

In [9]:
l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [11]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


In [32]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time() - start) * 1000)

# numpy array
result = time.time()
result = a1 + a2
print("numpy took: ", time.time() * 1000)

python list took:  371.9501495361328
numpy took:  1585747296669.731


In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b = np.array([[0, 1, 4, 7], [2, 3, 4, 5], [6, 7, 8, 9]], dtype = np.float64)
print(b)
print()
print("La dimension de b est: ", b.ndim)
x = b[:2, :]
x = x.ravel()
print(x)
print(b.min())

[[0. 1. 4. 7.]
 [2. 3. 4. 5.]
 [6. 7. 8. 9.]]

La dimension de b est:  2
[0. 1. 4. 7. 2. 3. 4. 5.]
0.0


In [30]:
b = np.array([[0, 1, 4, 7], [2, 3, 4, 5], [6, 7, 8, 9]], dtype = complex)
print(b)

[[0.+0.j 1.+0.j 4.+0.j 7.+0.j]
 [2.+0.j 3.+0.j 4.+0.j 5.+0.j]
 [6.+0.j 7.+0.j 8.+0.j 9.+0.j]]


In [55]:
t1 = np.linspace(1, 20, 10)#dans la botte le max c'est 1 et le min c'est 20
t2 = np.linspace(1,5, 5)#on a 5 nombre donc le max c'est 1 et le min c'est 5
x1 = t1

print("  lkjmlkjlkmj",type(x1))
print("t1 = {} \n \n t2 = {}".format(t1,t2))

print(np.shape(t2))
print(t2.shape)
t3 = t2.shape
t4 = t2.reshape(5,1)
print()
print(t4)
print(t4.shape)

print()
t5 = t4.ravel()
print(t5)
print(x1.min())
print(t5.max())
print(t5.sum())


  lkjmlkjlkmj <class 'numpy.ndarray'>
t1 = [ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ] 
 
 t2 = [1. 2. 3. 4. 5.]
(5,)
(5,)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
(5, 1)

[1. 2. 3. 4. 5.]
1.0
5.0
15.0


In [60]:
matA = np.array([[1,2], [3,4],[5,6]])

print(matA)
print()
print(matA.sum(axis = 0))
print()
print(matA.sum(axis = 1))

[[1 2]
 [3 4]
 [5 6]]

[ 9 12]

[ 3  7 11]
