# ################REVISION PYTHON #####################TELESCO#######################################################

In [20]:
from numpy import *

####Avec les structure de donnée {Array()} on préciser le type de donnée ensuite il devient impossible d'inserer un type autre

arr1 = array([1, 12, 3, 4], int)
#arr2 = array([1, 2, 3, 4], float)
arr1.sort()
print(arr1)
print(arr2)

#ici la copie est faite tel que: meme adresse memoire les modificatin de l'un affecte l'autre
print()
arr2 = arr1
arr1[0] = 10
print(id(arr1))
print(id(arr2))
print(arr1)
print(arr2)
#ici la copie est faite tel que: l'adresse est différent mais les modification affecte l'autre
print()
arr2 = arr1.view
arr1[0] = 10
print(id(arr1))
print(id(arr2))
print(arr1)
print(arr2)
#ici la copie est faite tel que: l'adresse est différente mais les modif de l'un n'affectent pas l'autre
print()
arr2 = arr1.copy()
arr1[0] = 10
print(id(arr1))
print(id(arr2))
print(arr1)
print(arr2)

[ 1  3  4 12]
[10  3  4 12]

34604374336
34604374336
[10  3  4 12]
[10  3  4 12]

34604374336
34572216344
[10  3  4 12]
<built-in method view of numpy.ndarray object at 0x000000080E94D940>

34604374336
34604394896
[10  3  4 12]
[10  3  4 12]


In [23]:
#ici la copie est faite tel que: l'adresse est différente mais les modif de l'un n'affectent pas l'autre

arr1 = array([1, 12, 3, 4], int)
arr2 = array([1, 2, 3, 4], float)
arr2 = arr1.copy()
arr1[0] = 10
print(id(arr1))
print(id(arr2))
print(arr1)
print(arr2)

34604303504
34604191056
[10 12  3  4]
[ 1 12  3  4]


In [29]:
m = matrix('1 2 8; 1 2 5; 7 8 9')
m1 = matrix('1 0 8; 1 3 5; 3 8 9')

m2 = m * m1
print(diagonal(m2))


[ 27  46 177]


In [ ]:
##################FONCTION LAMBDA ################## REVISION FONCTION LAMBDA

In [4]:
from functools import reduce

#def add_all(a, b): ### L'équivalent de la fonction {lambda} sera lambda a,b: a+b
    #return a+b

    
"""{filter(func, iterable)} prend ne entrée un tuple et retourne un tuple"""
"""{map(func, iterable)} prend en entrée un dict et retourne un dict"""
"""{reduce(func, sequence)} prend une sequence et retourne une sequence"""

    
nums = [3, 2, 6, 8, 4, 6, 2, 9]

evens = list(filter(lambda n : n%2==0, nums))#il prend chaque élément du tableau {nums} pour appliquer la fonction lambda dessus

doubles = list(map(lambda n : n*2, evens))
print(doubles)
sum = reduce(lambda a,b: a+b, doubles)

print(sum)

[4, 12, 16, 8, 12, 4]
56


In [6]:
############################# DECORATOR ################### DECORATOR

In [8]:
def div(a, b):
    print(a/b)
    

    
def smart_div(func):
    
    def inner(a, b):
        if a < b:
            a,b = b,a
            return func(a,b)
    return inner

div = smart_div(div)

div(2, 4)
    
    
    
    

2.0
