In [5]:
import numpy as np

np.random.seed(0)
a = np.random.randint(0, 10, [2, 3])
print(a)
print("somme")
print(a.sum(axis=0))
print("cumusom")
print(a.cumsum())
print("produit")
print(a.prod(axis=1))
print("cumuprod")
print(a.cumprod())
print("min")
print(a.min(axis=0))
print("argmin")
print(a.argmin(axis=0))
print("max")
print(a.max(axis=0))
print("argmax")
print(a.argmax(axis=1))
print("sort")
print(a.sort(axis=0))
print("argsort")
print(a.argsort(axis=1))

[[5 0 3]
 [3 7 9]]
somme
[ 8  7 12]
cumusom
[ 5  5  8 11 18 27]
produit
[  0 189]
cumuprod
[5 0 0 0 0 0]
min
[3 0 3]
argmin
[1 0 0]
max
[5 7 9]
argmax
[0 2]
sort
None
argsort
[[1 0 2]
 [0 1 2]]


In [7]:
print("sinus")
print(np.sin(a))
print("sinius hyperbolique")
print(np.sinh(a))
print("cosisus")
print(np.cos(a))
print("cosinus hyperbolique")
print(np.cosh(a))
print("tangente")
print(np.tan(a))
print("exponetiel")
print(np.exp(a))
print("logaritmique")
print(np.log(a))


sinus
[[ 0.14112001  0.          0.14112001]
 [-0.95892427  0.6569866   0.41211849]]
sinius hyperbolique
[[  10.01787493    0.           10.01787493]
 [  74.20321058  548.31612327 4051.54190208]]
cosisus
[[-0.9899925   1.         -0.9899925 ]
 [ 0.28366219  0.75390225 -0.91113026]]
cosinus hyperbolique
[[1.00676620e+01 1.00000000e+00 1.00676620e+01]
 [7.42099485e+01 5.48317035e+02 4.05154203e+03]]
tangente
[[-0.14254654  0.         -0.14254654]
 [-3.38051501  0.87144798 -0.45231566]]
exponetiel
[[2.00855369e+01 1.00000000e+00 2.00855369e+01]
 [1.48413159e+02 1.09663316e+03 8.10308393e+03]]
logaritmique
[[1.09861229       -inf 1.09861229]
 [1.60943791 1.94591015 2.19722458]]


C:\Users\ANGO\anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log
  


# statistique avec numpy

print("calcul de la moyenne")
print(a.mean())
prinrt("ecartype")
print(a.std())
print("Variance")   
print(a.var())
#on peut aussi le faire avec les axis........