In [16]:
import numpy as np

A = np.array([0, 1, 4, 9, 16, 25, 36, 49, 64, 81])#CREATION D'UN TABLEAU "np.array"
print(A.ndim)
print(type(A))
print(type(A.shape))#
print(A.shape)
print(A)

1
<class 'numpy.ndarray'>
<class 'tuple'>
(10,)
[ 0  1  4  9 16 25 36 49 64 81]


In [6]:
B = np.zeros((3, 2))
print(B.ndim)
print(B.shape)
print(B)

2
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
C = np.ones((3, 4))#INITIALISE LE TABLEAU AVEC LES "1"
print(C.ndim)
print(C.shape)
print(C)
print(C.size)

2
(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12


In [13]:
#on crée un tableau 2 lignes 3 colones qu'on rempli avec le chiffre 9
D = np.full((2, 3), 9)
print(D.ndim)#AFFICHE LA DIMENSION NB:une dimension == une ligne et non une colone
print(D.shape)#AFFICHE LE NOMBRE E LIGNE ET DE COLONES
print(D)
print(D.size)

2
(2, 3)
[[9 9 9]
 [9 9 9]]
6
