In [56]:
import numpy as np

np.random.seed(0)
a = np.random.randint(0, 10, [5, 5])
a

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])


# Methode ndarray


In [27]:
a.sum(axis=1) #la somme suivant l'axe des lignes

array([26, 27])

In [57]:
print(a.cumsum()) #ici on fait la somme cummulée 
print(a.prod())#ici c'est le produit on peux aussi le faire suivant les axes
print(a.cumprod())
print(a.min())
print(a.max())

[  5   5   8  11  18  27  30  35  37  41  48  54  62  70  71  77  84  91
  99 100 105 114 122 131 135]
0
[5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
0
9


In [30]:
#pour avoir la position du minimum (index) dans notre axe '0'
print(a.argmin(axis = 0))

[0 0 0 0 1]


In [58]:
#print(a.sort())#ici on tri simplement le table/ on peut aussi le faire suivant un axe(ligne ou colone)
print(a)
print()
print(a.argsort(axis = 0))#celui si tri le tableau et affiche les arguments correspondant aux éléments triés

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]

[[0 0 0 1 2]
 [4 1 1 0 3]
 [3 2 3 2 1]
 [2 3 2 3 4]
 [1 4 4 4 0]]


In [59]:
print(np.exp(a)) #exponentiel de chaque nombre du tableu
print()
print(np.log(a))#on obtient une erreur car log(0) n'existe pas...
print()
print(np.cos(a))
print()
print(np.cosh(a))
print()
print(np.sin(a))
print()
print(np.sinh(a))#ici on affiche le sinus hyperbolique


[[1.48413159e+02 1.00000000e+00 2.00855369e+01 2.00855369e+01
  1.09663316e+03]
 [8.10308393e+03 2.00855369e+01 1.48413159e+02 7.38905610e+00
  5.45981500e+01]
 [1.09663316e+03 4.03428793e+02 2.98095799e+03 2.98095799e+03
  2.71828183e+00]
 [4.03428793e+02 1.09663316e+03 1.09663316e+03 2.98095799e+03
  2.71828183e+00]
 [1.48413159e+02 8.10308393e+03 2.98095799e+03 8.10308393e+03
  5.45981500e+01]]

[[1.60943791       -inf 1.09861229 1.09861229 1.94591015]
 [2.19722458 1.09861229 1.60943791 0.69314718 1.38629436]
 [1.94591015 1.79175947 2.07944154 2.07944154 0.        ]
 [1.79175947 1.94591015 1.94591015 2.07944154 0.        ]
 [1.60943791 2.19722458 2.07944154 2.19722458 1.38629436]]

[[ 0.28366219  1.         -0.9899925  -0.9899925   0.75390225]
 [-0.91113026 -0.9899925   0.28366219 -0.41614684 -0.65364362]
 [ 0.75390225  0.96017029 -0.14550003 -0.14550003  0.54030231]
 [ 0.96017029  0.75390225  0.75390225 -0.14550003  0.54030231]
 [ 0.28366219 -0.91113026 -0.14550003 -0.91113026 -0.6

C:\Users\ANGO\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


# STATISTIQUES 

In [60]:
print(a)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]


In [61]:
a.min()

0

In [62]:
a.mean() # La moyenne du tableau

5.4

In [63]:
a.std() #L'écartype du tableau

2.6683328128252666

In [64]:
a.var()#La variance du tableau

7.12

In [65]:
#MATRICE DE CORELATION
print(np.corrcoef(a))
print()
print(np.corrcoef(a)[0, 1]) #on utilise l'indexing pour obtenir l'elt ligne '0' col '1'



[[ 1.          0.39741307 -0.59190035 -0.77390599 -0.89934617]
 [ 0.39741307  1.          0.09521171 -0.11337365 -0.59181844]
 [-0.59190035  0.09521171  1.          0.9579589   0.6947088 ]
 [-0.77390599 -0.11337365  0.9579589   1.          0.84515425]
 [-0.89934617 -0.59181844  0.6947088   0.84515425  1.        ]]

0.39741306906256163


In [73]:
#Trouver le nombre d'OCCURENCE d'un élement dans un tableau
#on obtient 2 tableaux 
#le premier ressence tous les nombres présents dans le tableau en faisant(np.unique(a))
#le second ressence le nombre d'occurence de chaque élément en ajoutant(np.unique(a, return_counts = True))
print(a)
print()
print(np.unique(a))
print(np.unique(a, return_counts = True))
#on va crée 2 tableau values et counts qui vont recupéré les 2 tableaux crée
print("\n")
values, counts = np.unique(a, return_counts = True)
#on va trié le tableau counts
print(counts.argsort())
print(values[counts.argsort()])
print("\n \n dfs-----n -------------")

for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valuer {i} occurence {j}')


[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]

[0 1 2 3 4 5 6 7 8 9]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64))


[0 2 1 4 6 3 5 9 7 8]
[0 2 1 4 6 3 5 9 7 8]

 
 dfs-----n -------------
valuer 0 occurence 1
valuer 2 occurence 1
valuer 1 occurence 2
valuer 4 occurence 2
valuer 6 occurence 2
valuer 3 occurence 3
valuer 5 occurence 3
valuer 9 occurence 3
valuer 7 occurence 4
valuer 8 occurence 4


# NAN Corrections

In [90]:
#NAN = not a number lors des calculs statistiques il pose pb car il n'est pas un nombre
b = np.random.randn(5, 5)

b[0, 2] = np.nan
b[4, 3] = np.nan

print(b)
print()
print(b.mean())

# On peut alors resoudre le problème en calculant sans prendre en compte le NAN

print(np.nanstd(b))
print(np.nanmean(b))
print(np.nanvar(b))
print()

# On peut également compter le nombre de NAN présent dans un tableau

print(np.isnan(b))
print("le nombre de nan est: ", np.isnan(b).sum())
# On peut Trouver le pourcentage de nan présent dans notre tableau
print("le pourcentage de nan est: ", np.isnan(b).sum()/b.size)

#On peut essayer de remplacer tous les nan présent dans notre tableau par des valeurs souhaité

b[np.isnan(b)] = 0
print(np.isnan(b))




[[ 1.73272119  0.68450111         nan  0.14206181  1.51999486]
 [ 1.71958931  0.92950511  0.58222459 -2.09460307  0.12372191]
 [-0.13010695  0.09395323  0.94304609 -2.73967717 -0.56931205]
 [ 0.26990435 -0.46684555 -1.41690611  0.86896349  0.27687191]
 [-0.97110457  0.3148172   0.82158571         nan  0.8005648 ]]

nan
1.1050117542119606
0.1493683127375555
1.2210509769465943

[[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False  True False]]
le nombre de nan est:  2
le pourcentage de nan est:  0.08
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


# Algebre Linéaire

In [107]:
a = np.ones((2, 3))
b = np.ones((3, 2))

print(f'a \n {a}\n b \n {b}')
print()

#On peut trouve la Transposée de a
print(a.T.shape)
print()
#On peut faire le produit matritielle de a et b
print("a X b\n",a.dot(b))
print()
print("b X a\n",b.dot(a))


a 
 [[1. 1. 1.]
 [1. 1. 1.]]
 b 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

(3, 2)

a X b
 [[3. 3.]
 [3. 3.]]

b X a
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [110]:
#Obtenons un matrice carée aléatoire de lignes et colones

a = np.random.randint(0, 10, [3, 3])
print(a)

[[7 7 6]
 [2 6 0]
 [2 7 7]]


In [118]:
#On peut calculer le determinant de A
print(np.linalg.det(a))
#Vu que notre det n'est pas égale a zéro on peut l'inverser
print()
print(np.linalg.inv(a))

#On peut essayer d'obtenir les valeurs propres et les vecteur propres
#on obtient 2 matrices 1ere les valeures propres 2eme les vecteurs propres
print("\nValeurs propres et veucteurs propres")
print(np.linalg.eig(a))

207.99999999999997

[[ 0.20192308 -0.03365385 -0.17307692]
 [-0.06730769  0.17788462  0.05769231]
 [ 0.00961538 -0.16826923  0.13461538]]

Valeurs propres et veucteurs propres
(array([13. +0.j        ,  3.5+1.93649167j,  3.5-1.93649167j]), array([[-8.09490512e-01+0.j        , -7.07106781e-01+0.j        ,
        -7.07106781e-01-0.j        ],
       [-2.31283003e-01+0.j        ,  3.53553391e-01+0.27386128j,
         3.53553391e-01-0.27386128j],
       [-5.39660341e-01+0.j        ,  4.44089210e-16-0.54772256j,
         4.44089210e-16+0.54772256j]]))
