In [7]:
import numpy as np

np.random.seed(0)
a = np.random.randint(0, 10, [2, 3])
print(a)
print("somme")
print(a.sum(axis=0))
print("cumusom")
print(a.cumsum())
print("produit")
print(a.prod(axis=1))
print("cumuprod")
print(a.cumprod())

[[5 0 3]
 [3 7 9]]
somme
[ 8  7 12]
cumusom
[ 5  5  8 11 18 27]
produit
[  0 189]

[5 0 0 0 0 0]
