In [54]:
# numpy

import numpy as np

A = np.array([0, 1, 4, 9, 16, 25, 36, 49, 64, 81])#CREATION D'UN TABLEAU AVEC "np.array"
print(A.ndim)
print(type(A))
print(type(A.shape))#UN SHAPE EST UN TUPLE
print(A.shape)
print(A)

1
<class 'numpy.ndarray'>
<class 'tuple'>
(10,)
[ 0  1  4  9 16 25 36 49 64 81]


In [60]:
B = np.zeros((3, 2))
print(B.ndim)
print(B.shape)
print(B)

2
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
C = np.ones((3, 4))#INITIALISE LE TABLEAU AVEC LES "1"
print(C.ndim)
print(C.shape)
print(C)
print(C.size)

2
(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12


In [22]:
#on crée un tableau 2 lignes 3 colones qu'on rempli avec le chiffre 9
D = np.full((2, 3), 9)
E = np.array([0, 1, 2])
print(E.ndim)
print()
F = E * D
print(F)
print()
print(D.ndim)#AFFICHE LA DIMENSION NB:une dimension == une ligne et non une colone
print(D.shape)#AFFICHE LE NOMBRE E LIGNE ET DE COLONES
print(D)
print(D.size)

1

[[ 0  9 18]
 [ 0  9 18]]

2
(2, 3)
[[9 9 9]
 [9 9 9]]
6


In [25]:
#affiche un tableau de 3 ligne 4 colones avec la distribution aléatoire des des nombre de part et d'autre de "0"
#ceci grace a la fonction "random.randn"
G = np.random.randn(3, 4)
print(G)
#np.random.seed(0)

[[ 0.39879908 -0.66143965 -0.7221689   0.13017785]
 [-0.6271604   1.59826198 -0.66295093 -1.59988126]
 [ 1.63107377  2.02149484  0.41470486  0.3449375 ]]


In [31]:
#CREE UN MATRICE IDENTITE
H = np.eye(4)
print(H)
print(H.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2


In [64]:
#CREE une matrice a une dimension dans lequel on precise le nombre d'éléments,debut et fin puis la quantité qu'on veut
I = np.linspace(0, 10, 20)
print(I)
print(I.ndim)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
1


In [69]:
#CREE une matrice a une dimension donnant l'intervalle où des nombres voulu puis le "pas"
K = np.arange(0, 50, 1)
print(K)
print(K.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
1


NameError: name 'shape' is not defined

In [33]:
#QUELQUE soit la fonction choisie on peut utiliser un "4e" le <<dtype>> pour donner la precision sur la taille du nbr
I = np.linspace(0, 10, 20, dtype = np.float16 )
print(I)
print(I.ndim)

[ 0.      0.5264  1.053   1.579   2.105   2.63    3.158   3.684   4.21
  4.74    5.26    5.79    6.316   6.844   7.367   7.895   8.42    8.945
  9.48   10.    ]
1


# MANIPULATION


In [44]:
#ON PEUT CONCATENER 2 TABLEAUX PAR ------------COLONE------------ avec 
#<<np.hstack((matricA,matriceB))>> == np.concatenate((matricA,matriceB), axis = 0)

mat1 = np.zeros((3, 2))
mat2 = np.ones((3, 2))
L = np.hstack((mat1, mat2))
print(L.shape)
print()
print(mat1)
print()
print(mat2)
print()
print(L)

(3, 4)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [43]:
#ON PEUT CONCATENER 2 TABLEAUX PAR ----COLONE-------- avec 
#<<np.vstack((matricA,matriceB))>> == np.concatenate((matricA,matriceB), axis = 1)

mat1 = np.zeros((3, 2))
mat2 = np.ones((3, 2))
M = np.vstack((mat1, mat2))
print(M.shape)
print()
print(mat1)
print()
print(mat2)
print()
print(M)

(6, 2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [45]:
#AVEC <<np.concatenate((mat1, mat2), axis=0) -->"0" pour concatener vers l'axe des 'x' et -->"1" pour l'axe des 'y'

N = np.concatenate((mat1, mat2), axis = 0)
O = np.concatenate((mat1, mat2), axis = 1)
print(N)
print()
print(O)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [50]:
#<<np.reshape((3, 4)) change une matrice M1(3,4) en M1'(6, 2) a condition que le M.size ne change pas (nb elements)

print(np.shape(O))
print(O)
print()
P = O.reshape((6, 2))
print(P)
print()
print(O.reshape((4, 3)))

(3, 4)
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]

[[0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]]

[[0. 0. 1.]
 [1. 0. 0.]
 [1. 1. 0.]
 [0. 1. 1.]]


In [52]:
#la methode ravel qui applatit une matrice et nous donne une seule ligne

Q = O.reshape((3, 4))
print(Q)
print()
Q = Q.ravel()
print(Q)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]

[0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
